# arxivの学問領域の指定
subject: 'cat:astro-ph.EP OR cat:astro-ph.SR'

# 検索キーワード
keywords:
        protoplanetary disk: 5
        protoplanetary disks: 5
        CB68: 5
        CB 68: 5
        planet formation: 5
        Ophiuchus: 4
        ALMA: 4
        low mass: 4
        protostar: 3
        envelope: 2
        outflow: 2

# 通知の閾値
score_threshold: 0
